# permissions for end users to view contracttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contracttests-viewer-role
rules:
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests/status
  verbs:
  - get
