# permissions for end users to edit contracttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contracttests-editor-role
rules:
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests/status
  verbs:
  - get
