
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.appstudio.qe
  resources:
  - contracttests/status
  verbs:
  - get
  - patch
  - update
